cpanm Bio::Perl
cpanm Moose
cpanm Log::Log4perl
cpanm Array::Utils
cpanm File::Grep
cpanm File::Which 
cpanm File::Slurper
cpanm Text::CSV
cpanm XML::Parser
cpanm Graph
cpanm Graph::Writer::Dot
cpanm File::Find::Rule
