import pandas as pd
import argparse

Parser= argparse.ArgumentParser(description='convert depth file to flatcount')
Parser.add_argument('-in_f', dest= 'f', help= 'Input file, which is the result of "samtools depth"')
Parser.add_argument('-out_f', dest= 'out_f', help= 'Output file')

args= Parser.parse_args()
f= args.f
out_f= args.out_f
# read a depth file generated by 'sam depth'
cov_df= pd.read_csv(f, sep= '\t', header= None, names= ['chrom', 'position', 'count'], index_col= None)
count_list= [c.zfill(6) for c in cov_df.loc[:,'count'].astype('str', copy= False).tolist()]
count_str= ''.join(count_list)

with open(out_f, 'w') as out_fh:
    out_fh.write('\t'+count_str)
