tmp_d: 'tmp'
result_d: '/net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/results'
working_dir: '/net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3'
stampy_exe: '/home/thkuo/bin/stampy-1.0.23/stampy.py'
#raxml_exe: '/home/thkuo/miniconda3/envs/phypal/bin/raxmlHPC-PTHREADS-AVX2'
raxml_exe: '/home/thkuo/miniconda3/envs/phypal/bin/raxmlHPC-PTHREADS'
cores: 16

##### files
#### sample wise
samples: '/net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/data/samples.tsv'
#### only one
reference_sequence: '/net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/data/reference/RefCln_UCBPP-PA14.fa'
reference_annotation: '/net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/data/reference/RefCln_UCBPP-PA14.gbk'
##roary_gpa:
tree: '/net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/results/Paeru.nwk'
##gpa_table:
##snps_table:
##expr_table:
##pheno_table: 
##ml_markdown:
