c_ac: true
c_ac_out: cont_ancrec
cmpr: false
cores: '20'
dif: true
dif_alpha: 0.05
dif_lfc: 0
dif_out: difxpr
dna_reads: /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/merged/data/samples.3.dna.tsv
dryrun: true
expr_table: expr.edit.tab
gp_data_dir: null
gp_kmer: '6'
gp_md: geno2pheno.md
gpa_table: gpa.mat
indel_table: indel.mat
ng: false
nonsyn_snps_table: ns-syn.mat
notemp: true
output_dir: results
phe_table: data/strains/pheno/phenotypes.edit.mat
project: test
ref_fa: data/reference/RefCln_UCBPP-PA14.fa
ref_gbk: data/reference/RefCln_UCBPP-PA14.gbk
rna_reads: /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/merged/data/samples.3.rna.tsv
seq2geno_env_dir: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/merged/lib
seq2geno_lib_dir: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/merged/lib
seq2geno_smk_dir: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/merged/smk
stampy_exe: null
syn_snps_table: s-syn.mat
tree: Paeru.nwk
workdir: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/merged
