samples: 'data/samples.tsv'
reference_sequence: 'data/reference/RefCln_UCBPP-PA14.fa'
reference_annotation: 'data/reference/RefCln_UCBPP-PA14.gbk'
#phenotypes: 
tmp_d: 'tmp'
result_d: '/net/metagenomics/data/from_moni/old.tzuhao/SNPsTest/results'
working_dir: '/net/metagenomics/data/from_moni/old.tzuhao/SNPsTest'
stampy_exe: '/home/thkuo/bin/stampy-1.0.23/stampy.py'
raxml_exe: '/home/thkuo/miniconda3/envs/phypal/bin/raxmlHPC-PTHREADS-AVX2'
#cores: 40
cores: 16
