#!/bin/bash -       
#description     :BWA-based method; the other parts are still the same 
#author		 :tku16
#==========

#align illumina reads using bwa and art-file for visualization
prefix=$1	# used to name the different output files
infile1=$2	# name of input fastq file containing the left end reads 
infile2=$3	# name of input fastq file containing the right end reads
reffiles=$4	# path and prefix of reference files
annofile=$5	# path to annotation file
Rannofile=$6	# path to annotation file

indexref=$reffiles
hashref=$reffiles
annotation=$annofile
Rannotation=$Rannofile


bwa mem -v 2 -M \
  -t 1 \
  -R $(echo "@RG\tID:snps\tSM:snps") \
  $reffiles $infile1 $infile2 > $prefix.sam 

#echo  "writing art file"
sam2art.pl -s 2 -p -4 $prefix.sam > $prefix.art

#echo  "writing sin file"
sam2art.pl -s 2 -l -p -4 $prefix.sam > $prefix.sin

#echo  "writing flat pileup file"
sam2art.pl -f -s 2 -p $prefix.sam > $prefix.flatcount

#echo  "making gene counts"
art2genecount.pl -b -a $prefix.sin -t tab -r $annotation > $prefix.rpg

#echo  "writing statistics"
sam_statistics.pl -r -p $prefix.sam > $prefix.stats
#genes_statistics.R $prefix.rpg $Rannotation $prefix.stats $prefix
