#!/bin/sh

# Step 1. ensure your Conda is installed
# Step 2. check where the folder of seq2geno is 
# Step 3. point SEQ2HOME to where seq2geno is located, and run the below lines, and add them in your home/.profile
export SEQ2GENO_HOME=$HOME/bin/seq2geno
export PATH=${realpath $SEQ2GENO_HOME}/main:$PATH
export PATH=${realpath $SEQ2GENO_HOME}/create_genml:$PATH
# Step 4. install the basic environment
conda create --file snakemake_env.yml
# Step 5. test if the basic environment is installed
source activate snakemake_env
source deactivate
